import Button from 'element-ui/lib/button';
import Col from 'element-ui/lib/col';
import Row from 'element-ui/lib/row';
import Menu from 'element-ui/lib/menu';
import Submenu from 'element-ui/lib/submenu';
import Form from 'element-ui/lib/form';
import MenuItem from 'element-ui/lib/menu-item';
import Input from 'element-ui/lib/input';
import FormItem from 'element-ui/lib/form-item';
import DatePicker from 'element-ui/lib/date-picker';
import Table from 'element-ui/lib/table';
import TableColumn from 'element-ui/lib/table-column';
import Pagination from 'element-ui/lib/pagination';
import Alert from 'element-ui/lib/alert';
import Autocomplete from 'element-ui/lib/autocomplete';
import Select from 'element-ui/lib/select';
import Card from 'element-ui/lib/card';
import Option from 'element-ui/lib/option';
import Progress from 'element-ui/lib/progress';
export default (Vue) => {
  // Vue.use(Button, Button.name);
  // Vue.use(Col.name, Col);
  // Vue.use(Row.name, Row);
  // Vue.use(Menu.name, Menu);
  // Vue.use(Submenu.name, Submenu);
  // Vue.use(Form.name, Form);
  // Vue.use(MenuItem.name, MenuItem);
  // Vue.use(Input.name, Input);
  // Vue.use(FormItem.name, FormItem);
  // Vue.use(DatePicker.name, DatePicker);
  // Vue.use(Table.name, Table);
  // Vue.use(TableColumn.name, TableColumn);
  // Vue.use(Pagination.name, Pagination);
  // Vue.use(Alert.name, Alert);
  // Vue.use(Autocomplete.name, Autocomplete);
  // Vue.use(Select.name, Select);
  // Vue.use(Card.name, Card);
  // Vue.use(Option.name, Option);
  // Vue.use(Progress.name, Progress);
  Vue.use(Button);
  Vue.use(Col);
  Vue.use(Row);
  Vue.use(Menu);
  Vue.use(Submenu);
  Vue.use(Form);
  Vue.use(MenuItem);
  Vue.use(Input);
  Vue.use(FormItem);
  Vue.use(DatePicker);
  Vue.use(Table);
  Vue.use(TableColumn);
  Vue.use(Pagination);
  Vue.use(Alert);
  Vue.use(Autocomplete);
  Vue.use(Select);
  Vue.use(Card);
  Vue.use(Option);
  Vue.use(Progress);
}
